# Generated by Django 5.0.2 on 2024-05-15 15:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('employee_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('role_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Role.role')),
            ],
        ),
    ]
