# Generated by Django 5.0.3 on 2024-04-03 03:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_salary'),
        ('Role', '0002_role_issue_date'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Role.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee'),
        ),
    ]
