# Generated by Django 5.0.4 on 2024-05-18 14:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Payment_Methode', '0001_initial'),
        ('Projects', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('payment_method', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Payment_Methode.payment_methode')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Projects.projects')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
