# Generated by Django 5.0.2 on 2024-03-26 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Methode', '0001_initial'),
        ('invoice_reciept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Payment_Methode.payment_methode'),
        ),
    ]
