# Generated by Django 5.0.4 on 2024-06-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reciept', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='user',
        ),
        migrations.AddField(
            model_name='payments',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payments',
            name='registration_type',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
