# Generated by Django 5.0.2 on 2024-04-21 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('invoice_reciept', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='project',
        ),
        migrations.AddField(
            model_name='payments',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
    ]
