# Generated by Django 5.0.3 on 2024-04-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reciept', '0002_payments_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='client',
        ),
    ]
