# Generated by Django 5.0.3 on 2024-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reciept', '0003_remove_payments_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
