# Generated by Django 5.0.4 on 2024-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Methode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_methode',
            name='pay_method_image',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
