# Generated by Django 5.0.3 on 2024-04-03 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Methode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_methode',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
