# Generated by Django 5.0.4 on 2024-06-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Methode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_methode',
            name='pay_method_image',
            field=models.CharField(max_length=100),
        ),
    ]
