# Generated by Django 5.0.2 on 2024-04-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment_Type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_description', models.CharField(default='unkown', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('payment_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment_Type.payment_type')),
            ],
        ),
    ]
