# Generated by Django 5.0.3 on 2024-03-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='project_id',
            new_name='project',
        ),
    ]
