# Generated by Django 5.0.3 on 2024-04-03 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projects_nootaayo_projects_client_and_more'),
        ('payment', '0002_rename_project_id_expense_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Projects.projects'),
        ),
    ]
