# Generated by Django 5.0.3 on 2024-04-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_expense_account_type_alter_expense_project'),
    ]

    
