# Generated by Django 5.0.3 on 2024-04-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Type', '0001_initial'),
        ('payment', '0004_remove_expense_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_description',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_Type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Payment_Type.payment_type'),
        ),
    ]
