# Generated by Django 5.0.3 on 2024-04-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Type', '0001_initial'),
        ('Projects', '0005_alter_projects_client'),
        ('payment', '0005_remove_expense_expense_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment_Type.payment_type'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.projects'),
        ),
    ]
