# Generated by Django 5.0.4 on 2024-05-06 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_image', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('document_image', models.ImageField(upload_to='')),
                ('issue_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
