# Generated by Django 5.0.2 on 2024-04-21 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('document', models.CharField(default='Unknown', max_length=100)),
                ('issue_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
