# Generated by Django 5.0.3 on 2024-04-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
