# Generated by Django 5.0.2 on 2024-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_image',
            field=models.CharField(max_length=100),
        ),
    ]
