# Generated by Django 5.0.2 on 2024-05-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_remove_client_phone_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
