# Generated by Django 5.0.3 on 2024-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_client_contact_person_client_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
