# Generated by Django 5.0.4 on 2024-04-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_client_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.FileField(default='Unknown', upload_to='documents/'),
        ),
    ]
