# Generated by Django 5.0.2 on 2024-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='615754310', max_length=100),
        ),
    ]
