# Generated by Django 5.0.2 on 2024-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
