# Generated by Django 5.0.2 on 2024-04-21 09:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Projects.projects')),
            ],
        ),
    ]
