# Generated by Django 5.0.2 on 2024-03-26 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0002_projects_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isuu_date', models.DateField()),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Projects.projects')),
            ],
        ),
    ]
