# Generated by Django 5.0.2 on 2024-03-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(max_length=50),
        ),
    ]
