# Generated by Django 5.0.2 on 2024-04-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0002_alter_material_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
