# Generated by Django 5.0.3 on 2024-04-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0003_alter_material_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='isuu_date',
            new_name='issue_date',
        ),
        migrations.AddField(
            model_name='material',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
