# Generated by Django 5.0.3 on 2024-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0004_rename_isuu_date_material_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
