# Generated by Django 5.0.4 on 2024-05-18 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='')),
                ('company_address', models.CharField(max_length=100)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
