# Generated by Django 5.0.4 on 2024-06-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_about',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='companies',
            name='company_phone',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
