# Generated by Django 5.0.2 on 2024-04-01 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temporary_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=100)),
                ('hour', models.DecimalField(decimal_places=2, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('register_date', models.DateTimeField()),
                ('Temporary_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporary_employee.temporary_employee')),
            ],
        ),
    ]
