# Generated by Django 5.0.2 on 2024-04-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary_salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarysalary',
            name='hour',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='temporarysalary',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
