# Generated by Django 5.0.3 on 2024-03-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('amount', models.DecimalField(max_digits= 10, decimal_places=2) ),
                
            ],
        ),
    ]
