# Generated by Django 5.0.4 on 2024-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='architecture',
            field=models.CharField(max_length=100),
        ),
    ]
