# Generated by Django 5.0.3 on 2024-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
