# Generated by Django 5.0.2 on 2024-06-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0002_alter_design_architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='architecture',
            field=models.ImageField(upload_to='designs/'),
        ),
    ]
