# Generated by Django 5.0.2 on 2024-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0003_alter_design_architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='architecture',
            field=models.CharField(max_length=100),
        ),
    ]
