# Generated by Django 5.0.2 on 2024-05-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_tasks_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
