# Generated by Django 5.0.2 on 2024-05-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='my20@gmail.com', max_length=254, unique=True),
        ),
    ]
