# Generated by Django 5.0.4 on 2024-05-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_Image',
            field=models.CharField(max_length=100),
        ),
    ]
