# Generated by Django 5.0.3 on 2024-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
