# Generated by Django 5.0.2 on 2024-05-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
