# Generated by Django 5.0.3 on 2024-04-07 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
