# Generated by Django 5.0.2 on 2024-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='messege',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
