# Generated by Django 5.0.4 on 2024-05-18 14:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Design', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_No', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('Agreements', models.CharField(max_length=10000)),
                ('budget', models.FloatField(default=0)),
                ('BudgetRemain', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('design', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Design.design')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
