# Generated by Django 5.0.2 on 2024-06-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_Manager',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
