# Generated by Django 5.0.3 on 2024-03-25 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
