# Generated by Django 5.0.4 on 2024-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='BudgetRemain',
            field=models.FloatField(default=0),
        ),
    ]
