# Generated by Django 5.0.3 on 2024-04-03 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_client_contact_person_client_document'),
        ('Projects', '0002_projects_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Nootaayo',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
    ]
