# Generated by Django 5.0.3 on 2024-04-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projects_nootaayo_projects_client_and_more'),
    ]

    
