# Generated by Django 5.0.3 on 2024-04-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_alter_client_issue_date'),
        ('Projects', '0004_remove_projects_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
    ]
