# Generated by Django 5.0.3 on 2024-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_alter_projects_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Nootaayo',
            field=models.CharField(max_length=100),
        ),
    ]
