<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-16 18:41
=======
# Generated by Django 5.0.3 on 2024-04-16 05:37
>>>>>>> f43842c53a36c8531c9d3781693b6f82ded91fc0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_alter_projects_end_date_alter_projects_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(),
        ),
    ]
