# Generated by Django 5.0.3 on 2024-04-11 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0004_alter_client_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issue_date', models.DateTimeField()),
                ('client_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
            ],
        ),
    ]
