# Generated by Django 5.0.2 on 2024-04-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('quntinty', models.IntegerField(max_length=50)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
