# Generated by Django 5.0.2 on 2024-04-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='quntinty',
            field=models.IntegerField(),
        ),
    ]
