# Generated by Django 5.0.2 on 2024-04-02 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0002_alter_budget_quntinty'),
        ('Config_Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='config_invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Config_Invoice.configinvoice'),
        ),
    ]
