# Generated by Django 5.0.3 on 2024-04-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0003_budget_config_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
