# Generated by Django 5.0.2 on 2024-05-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_image', models.ImageField(default='finish', upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Projects.projects')),
            ],
        ),
    ]
