# Generated by Django 5.0.4 on 2024-05-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_image',
            field=models.ImageField(default='finish', upload_to=''),
        ),
    ]
