# Generated by Django 5.0.2 on 2024-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
