# Generated by Django 5.0.2 on 2024-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_remove_tasks_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
