# Generated by Django 5.0.2 on 2024-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_alter_tasks_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
