# Generated by Django 5.0.4 on 2024-05-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_tasks_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_image',
            field=models.CharField(max_length=100),
        ),
    ]
