# Generated by Django 5.0.4 on 2024-05-18 13:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_image', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('phone', models.CharField(default=None, max_length=100, unique=True)),
                ('document_image', models.ImageField(upload_to='')),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
